export declare type hash = string;
export declare type blknum = number;
export declare type date = string;
export declare type address = string;
export declare type timestamp = number;
export declare type wei = string;
export declare type int256 = string;
export declare type uint256 = string;
export declare type gas = string;
export declare type uint64 = number;
export declare type int64 = number;
export declare type double = number;
export declare type bytes32 = string;
export declare type TopicArray = string[];
export { Accountname, AccountnameArray } from '@modules/types/Accountname';
export { AssetHistory } from '@modules/types/AssetHistory';
export { Balance, BalanceArray } from '@modules/types/Balance';
export { Block, BlockArray } from '@modules/types/Block';
export { Chunk, ChunkArray } from '@modules/types/Chunk';
export { Function, FunctionArray } from '@modules/types/Function';
export { Logentry, LogentryArray } from '@modules/types/Logentry';
export { Monitor, MonitorArray } from '@modules/types/Monitor';
export { Parameter, ParameterArray } from '@modules/types/Parameter';
export { Receipt, ReceiptArray } from '@modules/types/Receipt';
export { Reconciliation, ReconciliationArray } from '@modules/types/Reconciliation';
export { Tag, TagArray } from '@modules/types/Tag';
export { Trace, TraceArray } from '@modules/types/Trace';
export { Traceaction, TraceactionArray } from '@modules/types/Traceaction';
export { Traceresult, TraceresultArray } from '@modules/types/Traceresult';
export { Transaction, TransactionArray } from '@modules/types/Transaction';
